config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"

  resources :users do
    resources :tasks
  end

  post "import" => "tasks#import", as: :tasks_import
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  enum status: { pending: 0, in_progress: 1, completed: 2 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @tasks = @user.tasks
  end

  def create
  end

  def update
  end

  def import
    puts "PARAMS: "
    puts params
    # accept the file from params
    # call our importer
    # return success or errors
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%= react_component("ImportPage", {importPath: tasks_import_path}) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1><%= @user.name %>'s Tasks</h1>
<% @tasks.each do |t| %>
  <p><%= t.title %></p>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<% @users.each do |u| %>
<p><%= link_to u.name, user_tasks_path(u.id) %></p>
<% end %>